kind: Project
apiVersion: project.openshift.io/v1
metadata:
  name: {{ .Values.cp4iNamespace }}
  annotations:
    argocd.argoproj.io/sync-wave: "-1"
  finalizers:
    - resources-finalizer.argocd.argoproj.io