apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ibm-catalog-source
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
  project: default
  source:
    path: /
    repoURL: '{{ .Values.spec.source.repoURL }}/ibm-catalog-source.git'
    targetRevision: {{ .Values.spec.source.targetRevision }}